name: "Test"
on:
  push:
    branches:
      - main

jobs:
  Explore-GitHub-Actions:
    runs-on: self-hosted
    steps:
      - run: echo "the job was automatically triggered by a ${{github.event_name}} event"
      - run: echo "the job is now running on a ${{runner.os}} server hosted by GitHub"
      - run: echo "the name of your branch is ${{github.ref}} and your responsitory is ${{github.repository}}"

      - name: Check out repository code
        uses: actions/checkout@v2
      - run: echo "the ${{github.repository}} repository has been cloned to the runner"

      - name: List files in the repository
        run: | 
          ls ${{github.workspace}}

      - run: echo "this jobs status is:${{job.status}}"  

